/* eslint-disable security/detect-non-literal-fs-filename -- The phase 1 integration test writes its report beneath the OS temp directory and reads repository-relative source files under the real worktree root. */
/**
 * Task 2 tests for read-only Phase 1 discovery.
 *
 * Static "no reference", low coverage, and a single unexercised environment are leads only: they must never
 * become a deadness conclusion. The three named tests below are the verbatim contract from the task brief;
 * the fixture sources intentionally exercise dynamic import, reflection/DI, shell/platform branching,
 * schema/template/RTM/generated inputs, and test-only helpers.
 */

import { execFile } from 'node:child_process';
import { promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

import { afterAll, describe, expect, it } from 'vitest';

import type {
  CommandEvidence,
  FalsePositiveContext,
  Phase1CandidateLead,
  RevisionIdentity,
  StaticReference,
} from '../logic/code-health-contract.js';
import {
  buildStaticInventory,
  checkFalsePositiveGuards,
  deriveFalsePositiveContext,
  mergeDynamicTrace,
  type Phase1Scenario,
} from '../logic/code-health-phase1-logic.js';
import { runPhase1, PHASE1_USAGE_DETAIL } from '../cli/code-health-phase1.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '../../..');

const revision: RevisionIdentity = {
  commitSha: 'a'.repeat(40),
  treeSha: 'b'.repeat(40),
  sourceBundleSha256: 'c'.repeat(64),
  analyzedAt: '2026-09-07T00:00:00.000Z',
};
const hash = 'd'.repeat(64);

const emptyContext: FalsePositiveContext = {
  dynamicImports: [],
  reflection: [],
  platforms: [],
  schemas: [],
  templates: [],
  rtmIds: [],
  testHelpers: [],
  generatedReferences: [],
  externalContracts: [],
};

function observedCommand(
  exitCode: number | null,
  observation: CommandEvidence['observation'] = 'observed',
): CommandEvidence {
  return {
    command: 'node',
    cwd: '.',
    environment: {},
    platform: 'win32',
    toolVersions: {},
    startedAt: '2026-09-07T00:00:00.000Z',
    endedAt: '2026-09-07T00:00:01.000Z',
    exitCode,
    observation,
    rawOutputPath: '.w-model/code-health/phase1/raw/probe.log',
    rawOutputSha256: 'e'.repeat(64),
  };
}

/** Minimal Git fixture environment mirroring the audit boundary in code-health-evidence.test.ts. */
const GIT_ENV = {
  GIT_CONFIG_NOSYSTEM: '1',
  GIT_CONFIG_GLOBAL: process.platform === 'win32' ? 'NUL' : '/dev/null',
  GIT_TERMINAL_PROMPT: '0',
  GIT_AUTHOR_NAME: 'code-health-p1',
  GIT_AUTHOR_EMAIL: 'code-health-p1@example.test',
  GIT_COMMITTER_NAME: 'code-health-p1',
  GIT_COMMITTER_EMAIL: 'code-health-p1@example.test',
  PATH: process.env.PATH,
  PATHEXT: process.env.PATHEXT,
  SYSTEMROOT: process.env.SYSTEMROOT,
  SYSTEMDRIVE: process.env.SYSTEMDRIVE,
  WINDIR: process.env.WINDIR,
  COMSPEC: process.env.COMSPEC,
  TEMP: process.env.TEMP,
  TMP: process.env.TMP,
  USERPROFILE: process.env.USERPROFILE,
} as NodeJS.ProcessEnv;

const execFileAsync = promisify(execFile);
const createdRoots: string[] = [];

async function git(root: string, args: string[]): Promise<string> {
  const { stdout } = await execFileAsync('git', args, {
    cwd: root,
    env: GIT_ENV,
    shell: false,
    windowsHide: true,
  });
  return stdout;
}

async function createTempGitRoot(): Promise<string> {
  const root = await fs.mkdtemp(path.join(tmpdir(), 'code-health-p1-changes-'));
  createdRoots.push(root);
  await git(root, ['init', '--quiet']);
  await fs.mkdir(path.join(root, 'src'), { recursive: true });
  await fs.writeFile(path.join(root, '.gitignore'), '.w-model/\n');
  await fs.writeFile(path.join(root, 'src', 'unused.ts'), 'export const unusedFunction = 1;\n');
  await git(root, ['add', '--all']);
  await git(root, ['-c', 'commit.gpgsign=false', 'commit', '--quiet', '-m', 'initial']);
  return root;
}

/** Fixture sources covering every false-positive mechanism the phase 1 guard must respect. */
const fixtureSources: Record<string, string> = {
  'src/plugin.ts': [
    '// AUTO-GENERATED plugin manifest; regenerated by the build.',
    "import type { Plugin } from './plugin-types.js';",
    '',
    '@injectable()',
    'export class PluginRegistry {',
    '  private readonly plugins = new Map<string, Plugin>();',
    '  register(name: string, plugin: Plugin): void {',
    '    this.plugins.set(name, plugin);',
    '  }',
    '}',
    '',
    'export const registry = new PluginRegistry();',
    "registry.register('PluginRegistry', registry);",
    "const paramTypes = Reflect.getMetadata('design:paramtypes', PluginRegistry);",
    'void paramTypes;',
    '',
  ].join('\n'),
  'src/cli.ts': [
    "import { registry } from './registry.js';",
    '',
    'export async function main(argv: string[]): Promise<void> {',
    '  const platform = process.platform;',
    '  const shell = platform === "win32" ? "powershell" : "bash";',
    '  const home = process.env.HOME;',
    '  const executable = process.execPath;',
    '  const separator = require("path").sep;',
    '  const eol = require("os").EOL;',
    "  const discovered = readdirSync('plugins');",
    "  const plugin = await import('./plugin.js');",
    "  registry.register('PluginRegistry', plugin.default);",
    "  app.get('/plugins/:name', (_req, res) => res.json(registry));",
    "  program.command('plugins list').option('--json', 'json output');",
    '  const handlers: Record<string, () => void> = { audit: auditHandler };',
    "  const selected = handlers[process.env.HANDLER ?? 'audit'];",
    "  const schema = JSON.parse(readFileSync('schema.json', 'utf8'));",
    "  const template = readFileSync('template.md', 'utf8');",
    "  const rtmId = 'REQ-1';",
    '  void [argv, shell, home, executable, separator, eol, discovered, selected, schema, template, rtmId];',
    '}',
    '',
  ].join('\n'),
  'schema.json': [
    '{',
    '  "$schema": "http://json-schema.org/draft-07/schema#",',
    '  "title": "REQ-1 retry schema",',
    '  "type": "object",',
    '  "properties": {',
    '    "retryCount": { "type": "integer" },',
    '    "serializedField": { "type": "string" }',
    '  },',
    '  "required": ["retryCount"]',
    '}',
    '',
  ].join('\n'),
  'template.md': [
    '# {{projectName}}',
    '',
    'Serialized field: {{serializedField}}',
    'Migration: {{fromVersion}} -> {{toVersion}}',
    'Requirement: REQ-1',
    '',
  ].join('\n'),
  'tests/setup.ts': [
    "import { expect } from 'vitest';",
    "import { buildSample } from './sample-builder.js';",
    "import { MockAdapter } from './mock-adapter.js';",
    "import { FakeClock } from './fake-clock.js';",
    '',
    'expect.extend({',
    '  toBeWithinRange(received: number, floor: number, ceiling: number): boolean {',
    '    return received >= floor && received <= ceiling;',
    '  },',
    '});',
    '',
    'export const clock = new FakeClock();',
    'export const adapter = new MockAdapter();',
    'export const sample = buildSample("user");',
    '',
  ].join('\n'),
};

const tempReport = path.join(tmpdir(), `code-health-phase1-report-${process.pid}.json`);

const scenarioMatrix: Phase1Scenario[] = [
  {
    id: 'smoke-current-platform',
    environment: `${process.platform}-node`,
    platform: process.platform,
    shell: process.platform === 'win32' ? 'git-bash' : 'bash',
    supported: true,
    command: 'node',
    args: ['--version'],
    cwd: '.',
    timeoutMs: 15_000,
    targets: ['w-model-dev/scripts/logic/code-health-contract.ts'],
  },
  {
    id: 'declared-unsupported',
    environment: 'win32-powershell',
    platform: 'win32',
    shell: 'powershell',
    supported: false,
    command: 'node',
    args: ['--version'],
    cwd: '.',
    timeoutMs: 15_000,
  },
];

afterAll(async () => {
  await fs.rm(tempReport, { force: true });
  await Promise.all(createdRoots.splice(0).map((root) => fs.rm(root, { recursive: true, force: true, maxRetries: 3 })));
});

describe('code-health phase 1 discovery', () => {
  it('static inventory 记录直接/间接引用、export/import、route/CLI registration、generated/schema/template/RTM 和 test helper', () => {
    const report = buildStaticInventory({
      files: ['src/plugin.ts', 'src/cli.ts', 'schema.json', 'template.md', 'tests/setup.ts'],
      sourceText: fixtureSources,
      revision,
    });
    expect(report.categories).toEqual(
      expect.arrayContaining([
        'dynamic-import',
        'reflection',
        'shell-platform',
        'schema-template-rtm',
        'test-only-helper',
      ]),
    );
    expect(report.references.some((r) => r.kind === 'string-symbol' && r.path === 'src/plugin.ts')).toBe(true);
  });

  it('静态无命中 + dynamic import/reflection 或未执行平台时只能是 unknown/blocked', () => {
    const staticReport = buildStaticInventory({
      files: ['src/plugin.ts', 'src/cli.ts', 'schema.json', 'template.md', 'tests/setup.ts'],
      sourceText: fixtureSources,
      revision,
    });
    const lead = mergeDynamicTrace(staticReport, {
      revision,
      scenarios: [
        {
          id: 'smoke-win',
          environment: 'win32-git-bash',
          reached: false,
          observation: 'unavailable',
        },
      ],
      rawTraceSha256: hash,
    });
    expect(
      checkFalsePositiveGuards(lead[0]!, {
        dynamicImports: ['src/plugin.ts'],
        reflection: ['PluginRegistry'],
        platforms: ['win32', 'linux'],
        schemas: ['schema.json'],
        templates: ['template.md'],
        rtmIds: ['REQ-1'],
        testHelpers: ['tests/setup.ts'],
        generatedReferences: [],
        externalContracts: [],
      }),
    ).not.toEqual([]);
    expect(lead[0]?.classification).toBe('unknown');
  });

  it('命令入口默认只读，报告包含候选 ID、revision、environment、commands、exit codes、hashes 和未执行场景', async () => {
    const result = await runPhase1({
      root: repoRoot,
      output: tempReport,
      scenarios: scenarioMatrix,
    });
    expect(result.exitCode).toBe(0);
    expect(result.report.candidates.every((c) => c.status === 'discovered')).toBe(true);
    expect(result.report.commands.every((c) => c.observation !== 'unverified')).toBe(true);
    expect(result.report.unexercisedScenarios.length).toBeGreaterThan(0);
    expect(result.changedFiles).toEqual([]);
  });

  it('静态 inventory 逐信号发现：decorator/DI、filesystem、config handler、path/EOL、shell、schema/template/migration/graph ID、matcher、test doubles', async () => {
    const signalsPath = path.resolve(here, '../samples/code-health/phase1/static/signals.json');
    const raw = await fs.readFile(signalsPath, 'utf8');
    const signals = JSON.parse(raw) as {
      revision: RevisionIdentity;
      files: string[];
      sourceText: Record<string, string>;
    };
    const report = buildStaticInventory({
      files: signals.files,
      sourceText: signals.sourceText,
      revision: signals.revision,
    });
    const has = (kind: StaticReference['kind'], symbol: string): boolean =>
      report.references.some((reference) => reference.kind === kind && reference.symbol === symbol);

    // dynamic import()
    expect(has('dynamic-import', './plugin.js')).toBe(true);
    // plugin registry / DI / decorator metadata
    expect(has('reflection', 'injectable')).toBe(true);
    expect(has('reflection', 'getMetadata')).toBe(true);
    expect(has('reflection', 'design:paramtypes')).toBe(true);
    // string-to-symbol
    expect(has('string-symbol', 'PluginRegistry')).toBe(true);
    // filesystem discovery (readdirSync)
    expect(has('dynamic-import', 'readdirSync')).toBe(true);
    // config-selected handler: computed member access + environment lookup
    expect(has('reflection', 'computed-member-access')).toBe(true);
    expect(has('shell-platform', 'process.env')).toBe(true);
    // process.platform / env / executable
    expect(has('shell-platform', 'process.platform')).toBe(true);
    expect(has('shell-platform', 'process.execPath')).toBe(true);
    // path separator / line ending
    expect(has('shell-platform', 'path')).toBe(true);
    expect(has('shell-platform', 'os')).toBe(true);
    // Shell/PowerShell literals
    expect(has('shell-platform', 'powershell')).toBe(true);
    expect(has('shell-platform', 'bash')).toBe(true);
    // schema field / template placeholder / serialized field
    expect(has('schema', 'schema.json')).toBe(true);
    expect(has('template', 'projectName')).toBe(true);
    expect(has('template', 'serializedField')).toBe(true);
    // migration
    expect(has('generated-input', 'migration')).toBe(true);
    // RTM IDs and non-REQ/RTM graph IDs
    expect(has('rtm', 'REQ-1')).toBe(true);
    expect(has('rtm', 'GRAPH-NODE-1')).toBe(true);
    // test-only helper file and custom matcher registration
    expect(has('test-helper', 'tests/setup.ts')).toBe(true);
    expect(has('test-helper', 'expect.extend')).toBe(true);
    // mock adapter / fake clock / sample builder references
    expect(has('import', './mock-adapter.js')).toBe(true);
    expect(has('import', './fake-clock.js')).toBe(true);
    expect(has('import', './sample-builder.js')).toBe(true);

    // A config-selected handler is a statically unresolved mechanism and must keep the lead non-candidate.
    const context = deriveFalsePositiveContext(report, ['win32']);
    const leads = mergeDynamicTrace(report, {
      revision: signals.revision,
      scenarios: [
        {
          id: 'signals-smoke',
          environment: 'current',
          reached: true,
          observation: 'observed',
          command: observedCommand(0),
        },
      ],
      rawTraceSha256: hash,
    });
    const violations = checkFalsePositiveGuards(leads[0]!, context);
    expect(violations.some((violation) => violation.startsWith('unresolved-mechanism:'))).toBe(true);
    // runPhase1 applies guard violations by demoting any would-be candidate to unknown.
    const guarded = leads[0]!;
    if (violations.length > 0 && guarded.classification === 'candidate') guarded.classification = 'unknown';
    expect(guarded.classification).not.toBe('candidate');
  });

  it('observed 但缺 command evidence 的场景不得判为 exercised（provenance 强制）', () => {
    const staticReport = buildStaticInventory({
      files: ['src/lonely.ts'],
      sourceText: { 'src/lonely.ts': 'export const lonely = 1;\n' },
      revision,
    });
    const leads = mergeDynamicTrace(staticReport, {
      revision,
      scenarios: [
        {
          id: 'observed-no-command',
          environment: 'current',
          reached: true,
          observation: 'observed',
        },
      ],
      rawTraceSha256: hash,
    });
    const lead = leads[0]!;
    const violations = checkFalsePositiveGuards(lead, emptyContext);
    expect(lead.classification).not.toBe('candidate');
    expect(violations.length).toBeGreaterThan(0);
  });

  it('lead 声称 observed+reached 但 dynamicScenarios 缺 command 时 guard 必须告警', () => {
    const lead = {
      candidateId: 'CHG-P1-20260907-002',
      classification: 'candidate',
      files: ['src/lonely.ts'],
      symbols: ['lonely'],
      staticReferences: [],
      dynamicScenarios: [
        {
          id: 'observed-no-command',
          environment: 'current',
          reached: true,
          observation: 'observed',
        },
      ],
      guardViolations: [],
      status: 'discovered',
    } as unknown as Phase1CandidateLead;
    expect(checkFalsePositiveGuards(lead, emptyContext).length).toBeGreaterThan(0);
  });

  it.each([
    ['exitCode=null', observedCommand(null)],
    ['command observation=unverified', observedCommand(0, 'unverified')],
  ])('command evidence %s 不算 exercised', (_label, command) => {
    const staticReport = buildStaticInventory({
      files: ['src/lonely.ts'],
      sourceText: { 'src/lonely.ts': 'export const lonely = 1;\n' },
      revision,
    });
    const leads = mergeDynamicTrace(staticReport, {
      revision,
      scenarios: [
        {
          id: 'fake-observed',
          environment: 'current',
          reached: true,
          observation: 'observed',
          command,
        },
      ],
      rawTraceSha256: hash,
    });
    const lead = leads[0]!;
    const violations = checkFalsePositiveGuards(lead, emptyContext);
    expect(lead.classification).not.toBe('candidate');
    expect(violations.length).toBeGreaterThan(0);
  });

  it('真实 observed + 数字 exitCode 且无其他误报机制时 lead 才可为 candidate', () => {
    const staticReport = buildStaticInventory({
      files: ['src/lonely.ts'],
      sourceText: { 'src/lonely.ts': 'export const lonely = 1;\n' },
      revision,
    });
    const leads = mergeDynamicTrace(staticReport, {
      revision,
      scenarios: [
        {
          id: 'verified',
          environment: 'current',
          reached: true,
          observation: 'observed',
          command: observedCommand(0),
        },
      ],
      rawTraceSha256: hash,
    });
    expect(leads[0]!.classification).toBe('candidate');
    expect(checkFalsePositiveGuards(leads[0]!, emptyContext)).toEqual([]);
  });

  it('changedFiles 来自前后 worktree 差分：预存在的工作树改动不被误报', async () => {
    const root = await createTempGitRoot();
    await fs.writeFile(path.join(root, 'src', 'unused.ts'), 'export const unusedFunction = 2;\n');
    const output = path.join(tmpdir(), `code-health-p1-changes-${process.pid}.json`);
    try {
      const result = await runPhase1({
        root,
        output,
        scenarios: [
          {
            id: 'smoke',
            environment: 'local',
            command: 'node',
            args: ['--version'],
            cwd: '.',
            targets: ['src/unused.ts'],
          },
        ],
      });
      expect(result.exitCode).toBe(0);
      expect(result.changedFiles).toEqual([]);
    } finally {
      await fs.rm(output, { force: true });
    }
  });

  it('read-only invariant 在工具改动工作树时非空并失败', async () => {
    const root = await createTempGitRoot();
    const output = path.join(tmpdir(), `code-health-p1-leak-${process.pid}.json`);
    let call = 0;
    try {
      const result = await runPhase1({
        root,
        output,
        scenarios: [
          {
            id: 'smoke',
            environment: 'local',
            command: 'node',
            args: ['--version'],
            cwd: '.',
            targets: ['src/unused.ts'],
          },
        ],
        readChangedFiles: async (_root, _paths) => (call++ === 0 ? [] : ['src/unused.ts']),
      });
      expect(result.changedFiles).toEqual(['src/unused.ts']);
      expect(result.exitCode).toBe(1);
    } finally {
      await fs.rm(output, { force: true });
    }
  });
});

describe('code-health-phase1 CLI usage surface', () => {
  it('usage detail states that changedFiles only covers analyzed targets', () => {
    expect(PHASE1_USAGE_DETAIL).toContain('usage: code-health-phase1.ts');
    expect(PHASE1_USAGE_DETAIL).toMatch(/changedFiles covers only analyzed targets/);
  });
});
