/* eslint-disable security/detect-non-literal-fs-filename -- The phase 1 integration test writes its report beneath the OS temp directory and reads repository-relative source files under the real worktree root. */
/**
 * Task 2 tests for read-only Phase 1 discovery.
 *
 * Static "no reference", low coverage, and a single unexercised environment are leads only: they must never
 * become a deadness conclusion. The three named tests below are the verbatim contract from the task brief;
 * the fixture sources intentionally exercise dynamic import, reflection/DI, shell/platform branching,
 * schema/template/RTM/generated inputs, and test-only helpers.
 */

import { promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { afterAll, describe, expect, it } from 'vitest';

import type { RevisionIdentity } from '../logic/code-health-contract.js';
import {
  buildStaticInventory,
  checkFalsePositiveGuards,
  mergeDynamicTrace,
  type Phase1Scenario,
} from '../logic/code-health-phase1-logic.js';
import { runPhase1 } from '../cli/code-health-phase1.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '../../..');

const revision: RevisionIdentity = {
  commitSha: 'a'.repeat(40),
  treeSha: 'b'.repeat(40),
  sourceBundleSha256: 'c'.repeat(64),
  analyzedAt: '2026-09-07T00:00:00.000Z',
};
const hash = 'd'.repeat(64);

/** Fixture sources covering every false-positive mechanism the phase 1 guard must respect. */
const fixtureSources: Record<string, string> = {
  'src/plugin.ts': [
    '// AUTO-GENERATED plugin manifest; regenerated by the build.',
    "import type { Plugin } from './plugin-types.js';",
    '',
    '@injectable()',
    'export class PluginRegistry {',
    '  private readonly plugins = new Map<string, Plugin>();',
    '  register(name: string, plugin: Plugin): void {',
    '    this.plugins.set(name, plugin);',
    '  }',
    '}',
    '',
    'export const registry = new PluginRegistry();',
    "registry.register('PluginRegistry', registry);",
    "const paramTypes = Reflect.getMetadata('design:paramtypes', PluginRegistry);",
    'void paramTypes;',
    '',
  ].join('\n'),
  'src/cli.ts': [
    "import { registry } from './registry.js';",
    '',
    'export async function main(argv: string[]): Promise<void> {',
    '  const platform = process.platform;',
    '  const shell = platform === "win32" ? "powershell" : "bash";',
    '  const home = process.env.HOME;',
    '  const executable = process.execPath;',
    '  const separator = require("path").sep;',
    '  const eol = require("os").EOL;',
    "  const discovered = readdirSync('plugins');",
    "  const plugin = await import('./plugin.js');",
    "  registry.register('PluginRegistry', plugin.default);",
    "  app.get('/plugins/:name', (_req, res) => res.json(registry));",
    "  program.command('plugins list').option('--json', 'json output');",
    '  const handlers: Record<string, () => void> = { audit: auditHandler };',
    "  const selected = handlers[process.env.HANDLER ?? 'audit'];",
    "  const schema = JSON.parse(readFileSync('schema.json', 'utf8'));",
    "  const template = readFileSync('template.md', 'utf8');",
    "  const rtmId = 'REQ-1';",
    '  void [argv, shell, home, executable, separator, eol, discovered, selected, schema, template, rtmId];',
    '}',
    '',
  ].join('\n'),
  'schema.json': [
    '{',
    '  "$schema": "http://json-schema.org/draft-07/schema#",',
    '  "title": "REQ-1 retry schema",',
    '  "type": "object",',
    '  "properties": {',
    '    "retryCount": { "type": "integer" },',
    '    "serializedField": { "type": "string" }',
    '  },',
    '  "required": ["retryCount"]',
    '}',
    '',
  ].join('\n'),
  'template.md': [
    '# {{projectName}}',
    '',
    'Serialized field: {{serializedField}}',
    'Migration: {{fromVersion}} -> {{toVersion}}',
    'Requirement: REQ-1',
    '',
  ].join('\n'),
  'tests/setup.ts': [
    "import { expect } from 'vitest';",
    "import { buildSample } from './sample-builder.js';",
    "import { MockAdapter } from './mock-adapter.js';",
    "import { FakeClock } from './fake-clock.js';",
    '',
    'expect.extend({',
    '  toBeWithinRange(received: number, floor: number, ceiling: number): boolean {',
    '    return received >= floor && received <= ceiling;',
    '  },',
    '});',
    '',
    'export const clock = new FakeClock();',
    'export const adapter = new MockAdapter();',
    'export const sample = buildSample("user");',
    '',
  ].join('\n'),
};

const tempReport = path.join(tmpdir(), `code-health-phase1-report-${process.pid}.json`);

const scenarioMatrix: Phase1Scenario[] = [
  {
    id: 'smoke-current-platform',
    environment: `${process.platform}-node`,
    platform: process.platform,
    shell: process.platform === 'win32' ? 'git-bash' : 'bash',
    supported: true,
    command: 'node',
    args: ['--version'],
    cwd: '.',
    timeoutMs: 15_000,
    targets: ['w-model-dev/scripts/logic/code-health-contract.ts'],
  },
  {
    id: 'declared-unsupported',
    environment: 'win32-powershell',
    platform: 'win32',
    shell: 'powershell',
    supported: false,
    command: 'node',
    args: ['--version'],
    cwd: '.',
    timeoutMs: 15_000,
  },
];

afterAll(async () => {
  await fs.rm(tempReport, { force: true });
});

describe('code-health phase 1 discovery', () => {
  it('static inventory 记录直接/间接引用、export/import、route/CLI registration、generated/schema/template/RTM 和 test helper', () => {
    const report = buildStaticInventory({
      files: ['src/plugin.ts', 'src/cli.ts', 'schema.json', 'template.md', 'tests/setup.ts'],
      sourceText: fixtureSources,
      revision,
    });
    expect(report.categories).toEqual(
      expect.arrayContaining([
        'dynamic-import',
        'reflection',
        'shell-platform',
        'schema-template-rtm',
        'test-only-helper',
      ]),
    );
    expect(report.references.some((r) => r.kind === 'string-symbol' && r.path === 'src/plugin.ts')).toBe(true);
  });

  it('静态无命中 + dynamic import/reflection 或未执行平台时只能是 unknown/blocked', () => {
    const staticReport = buildStaticInventory({
      files: ['src/plugin.ts', 'src/cli.ts', 'schema.json', 'template.md', 'tests/setup.ts'],
      sourceText: fixtureSources,
      revision,
    });
    const lead = mergeDynamicTrace(staticReport, {
      revision,
      scenarios: [{ id: 'smoke-win', environment: 'win32-git-bash', reached: false, observation: 'unavailable' }],
      rawTraceSha256: hash,
    });
    expect(
      checkFalsePositiveGuards(lead[0]!, {
        dynamicImports: ['src/plugin.ts'],
        reflection: ['PluginRegistry'],
        platforms: ['win32', 'linux'],
        schemas: ['schema.json'],
        templates: ['template.md'],
        rtmIds: ['REQ-1'],
        testHelpers: ['tests/setup.ts'],
        generatedReferences: [],
        externalContracts: [],
      }),
    ).not.toEqual([]);
    expect(lead[0]?.classification).toBe('unknown');
  });

  it('命令入口默认只读，报告包含候选 ID、revision、environment、commands、exit codes、hashes 和未执行场景', async () => {
    const result = await runPhase1({ root: repoRoot, output: tempReport, scenarios: scenarioMatrix });
    expect(result.exitCode).toBe(0);
    expect(result.report.candidates.every((c) => c.status === 'discovered')).toBe(true);
    expect(result.report.commands.every((c) => c.observation !== 'unverified')).toBe(true);
    expect(result.report.unexercisedScenarios.length).toBeGreaterThan(0);
    expect(result.changedFiles).toEqual([]);
  });
});
